/** *************************************************************************************
  * Copyright (c) 2026 Institute of Computing Technology, Chinese Academy of Sciences
  *
  * XiangShan is licensed under Mulan PSL v2.
  * You can use this software according to the terms and conditions of the Mulan PSL v2.
  * You may obtain a copy of Mulan PSL v2 at:
  * http://license.coscl.org.cn/MulanPSL2
  *
  * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
  * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
  * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
  * See the Mulan PSL v2 for more details.
  * *************************************************************************************
  */

package top

import chisel3._
import chisel3.util._
import freechips.rocketchip.amba.axi4._
import freechips.rocketchip.amba.axi4.AXI4Parameters._
import freechips.rocketchip.diplomacy._
import org.chipsalliance.cde.config.Parameters
import xscache.chi._
import xscache.chi.CHICohStates._
import xscache.openLLC.ReceiverLinkMonitor

/** Minimal single-RN CHI to AXI bridge for an L2 connected directly to memory.
  *
  * Coherent traffic is restricted to 64-byte cache lines. The bridge also accepts the
  * narrow NoSnp traffic generated by CoupledL2's MMIOBridge for high-address main memory.
  */
class NoLLCCHI2AXI(entries: Int = 128)(implicit p: Parameters) extends LazyModule {
  require(entries == 128, "NoLLCCHI2AXI is specialized for 128 outstanding transactions")

  val axi4node = AXI4MasterNode(Seq(AXI4MasterPortParameters(
    masters = Seq(AXI4MasterParameters(
      name = "nollc-chi2axi",
      id = IdRange(0, entries),
      aligned = true,
      maxFlight = Some(1)
    ))
  )))

  lazy val module = new NoLLCCHI2AXIImp(this, entries)
}

class NoLLCCHI2AXIImp(wrapper: NoLLCCHI2AXI, entries: Int)(implicit p: Parameters)
  extends LazyModuleImp(wrapper)
  with HasCHIOpcodes {

  require(DATA_WIDTH == 256, "NoLLCCHI2AXI requires a 256-bit CHI data channel")

  private val lineBytes = 64
  private val axiBeatBytes = DATA_WIDTH / 8
  private val beatsPerLine = lineBytes / axiBeatBytes
  private val slotBits = log2Ceil(entries)
  require(beatsPerLine == 2)

  val io = IO(new Bundle {
    val rn = Flipped(new PortIO)
    val nodeID = Input(UInt(NODEID_WIDTH.W))
    val occupancy = Output(UInt(log2Ceil(entries + 1).W))
    val highWatermark = Output(UInt(log2Ceil(entries + 1).W))
    val accepted = Output(UInt(32.W))
  })

  private val kindCohRead = 0.U(3.W)
  private val kindCohWrite = 1.U(3.W)
  private val kindLocal = 2.U(3.W)
  private val kindNoSnpRead = 3.U(3.W)
  private val kindNoSnpWrite = 4.U(3.W)

  class Slot extends Bundle {
    val valid = Bool()
    val kind = UInt(3.W)
    val addr = UInt(ADDR_WIDTH.W)
    val size = UInt(SIZE_WIDTH.W)
    val reqTxnID = UInt(TXNID_WIDTH.W)
    val reqSrcID = UInt(SRCID_WIDTH.W)
    val qos = UInt(QOS_WIDTH.W)
    val traceTag = Bool()
    val responseState = UInt(RESP_WIDTH.W)
    val expCompAck = Bool()
    val ackSeen = Bool()
    val ownsReqTxnID = Bool()
    val orderedNoSnp = Bool()
    val readReceiptNeeded = Bool()
    val arIssued = Bool()
    val readBeatsAccepted = UInt(2.W)
    val readFirstDelivered = Bool()
    val readLastDelivered = Bool()
    val rspSent = Bool()
    val rspDelivered = Bool()
    val earlyWriteComp = Bool()
    val awIssued = Bool()
    val writeDataSent = Bool()
    val bDone = Bool()
    val writeCompSent = Bool()
    val writeCompDelivered = Bool()
  }

  class ReadDataEntry extends Bundle {
    val slot = UInt(slotBits.W)
    val last = Bool()
    val dat = new CHIDAT
  }

  class RspEntry extends Bundle {
    val slot = UInt(slotBits.W)
    val rsp = new CHIRSP
  }

  val slots = RegInit(VecInit(Seq.fill(entries)(0.U.asTypeOf(new Slot))))
  val accepted = RegInit(0.U(32.W))
  val highWatermark = RegInit(0.U(log2Ceil(entries + 1).W))
  val occupancy = PopCount(slots.map(_.valid))
  io.occupancy := occupancy
  io.highWatermark := highWatermark
  io.accepted := accepted
  when (occupancy > highWatermark) {
    highWatermark := occupancy
  }

  val linkMonitor = Module(new ReceiverLinkMonitor)
  linkMonitor.io.in <> io.rn
  val rn = linkMonitor.io.out
  rn.rx.snp.valid := false.B
  rn.rx.snp.bits := 0.U.asTypeOf(new CHISNP)

  val (axi, edge) = wrapper.axi4node.out.head
  require(edge.bundle.dataBits == DATA_WIDTH)
  require(edge.bundle.idBits >= slotBits)
  require(
    edge.slave.minLatency >= 1,
    "NoLLCCHI2AXI requires at least one cycle from AXI address acceptance to response"
  )

  private def slotID(id: UInt): UInt = id(slotBits - 1, 0)
  private def paddedSlotID(id: UInt): UInt = id.pad(edge.bundle.idBits)
  private def oddParity(data: UInt): UInt =
    VecInit((0 until DATACHECK_WIDTH).map(i => data(8 * (i + 1) - 1, 8 * i).xorR ^ true.B)).asUInt

  val upstreamReq = rn.tx.req
  val reqOpcode = upstreamReq.bits.opcode
  val isCohRead = reqOpcode === ReadNotSharedDirty || reqOpcode === ReadUnique
  val isCohWrite = reqOpcode === WriteBackFull || reqOpcode === WriteCleanFull
  val isNoSnpRead = reqOpcode === ReadNoSnp
  val isNoSnpWritePtl = reqOpcode === WriteNoSnpPtl
  val isNoSnpWriteFull = reqOpcode === WriteNoSnpFull
  val isNoSnpWrite = isNoSnpWritePtl || isNoSnpWriteFull
  val isNoSnp = isNoSnpRead || isNoSnpWrite
  val isMakeUnique = reqOpcode === MakeUnique
  val isWriteEvictOrEvict = afterIssueEbOrElse(reqOpcode === WriteEvictOrEvict, false.B)
  val isLocalInvalidation = reqOpcode === Evict || isWriteEvictOrEvict ||
    reqOpcode === CleanShared || reqOpcode === CleanInvalid || reqOpcode === MakeInvalid
  val isLocal = isMakeUnique || isLocalInvalidation
  val isSupportedReq = isCohRead || isCohWrite || isNoSnp || isLocal

  val freeSlotOH = VecInit(slots.map(slot => !slot.valid)).asUInt
  val hasFreeSlot = freeSlotOH.orR
  val allocSlot = PriorityEncoder(freeSlotOH)
  val reqTxnIDBusy = VecInit(slots.map(slot =>
    slot.valid && slot.ownsReqTxnID && slot.reqTxnID === upstreamReq.bits.txnID
  )).asUInt.orR
  val sameLineBusy = VecInit(slots.map(slot =>
    slot.valid && slot.addr(ADDR_WIDTH - 1, 6) === upstreamReq.bits.addr(ADDR_WIDTH - 1, 6)
  )).asUInt.orR
  val activeNoSnp = VecInit(slots.map(slot =>
    slot.valid && (slot.kind === kindNoSnpRead || slot.kind === kindNoSnpWrite)
  )).asUInt.orR
  val activeOrderedNoSnp = VecInit(slots.map(slot => slot.valid && slot.orderedNoSnp)).asUInt.orR
  val incomingOrderedNoSnp = isNoSnp && upstreamReq.bits.order =/= OrderEncodings.None
  val activeMemorySlot = slots.map(_.valid).reduce(_ || _)
  val noSnpOrderConflict = (incomingOrderedNoSnp && activeMemorySlot) || activeOrderedNoSnp

  upstreamReq.ready := isSupportedReq && hasFreeSlot && !reqTxnIDBusy && !sameLineBusy &&
    !noSnpOrderConflict
  val allocate = upstreamReq.fire
  val reqSizeMask = ((1.U((ADDR_WIDTH + 1).W) << upstreamReq.bits.size) - 1.U)(ADDR_WIDTH - 1, 0)
  val noSnpOrderSupported = upstreamReq.bits.order === OrderEncodings.None ||
    upstreamReq.bits.order === OrderEncodings.RequestAccepted ||
    upstreamReq.bits.order === OrderEncodings.RequestOrder ||
    upstreamReq.bits.order === OrderEncodings.EndpointOrder

  when (upstreamReq.valid) {
    assert(isSupportedReq, "NoLLCCHI2AXI received an unsupported CHI request opcode")
    assert(reqOpcode =/= WriteEvictFull, "NoLLCCHI2AXI does not support WriteEvictFull")
    assert(!upstreamReq.bits.excl, "NoLLCCHI2AXI does not support exclusive requests")
    when (isCohRead || isCohWrite || isLocal) {
      assert(upstreamReq.bits.size === log2Ceil(lineBytes).U,
        "NoLLCCHI2AXI coherent requests must be 64 bytes")
      assert(upstreamReq.bits.addr(5, 0) === 0.U,
        "NoLLCCHI2AXI coherent requests must be cache-line aligned")
      assert(!upstreamReq.bits.memAttr.device, "NoLLCCHI2AXI does not support coherent Device memory")
      assert(upstreamReq.bits.order === OrderEncodings.None,
        "NoLLCCHI2AXI does not implement ordered coherent requests")
    }
    when (isCohWrite) {
      assert(upstreamReq.bits.memAttr.ewa, "NoLLCCHI2AXI coherent writes require EWA")
    }
    when (isNoSnp) {
      assert(!upstreamReq.bits.memAttr.device,
        "NoLLCCHI2AXI NoSnp support is restricted to main memory")
      assert(upstreamReq.bits.size <= log2Ceil(lineBytes).U,
        "NoLLCCHI2AXI NoSnp request is larger than a cache line")
      assert((upstreamReq.bits.addr & reqSizeMask) === 0.U,
        "NoLLCCHI2AXI NoSnp request is not naturally aligned")
      assert(noSnpOrderSupported, "NoLLCCHI2AXI received an unsupported NoSnp Order")
      assert(!upstreamReq.bits.expCompAck, "NoLLCCHI2AXI NoSnp requests cannot require CompAck")
    }
    when (isNoSnpWritePtl) {
      assert(upstreamReq.bits.size <= log2Ceil(axiBeatBytes).U,
        "NoLLCCHI2AXI WriteNoSnpPtl must fit in one AXI beat")
    }
    when (isNoSnpRead) {
      assert(upstreamReq.bits.size <= log2Ceil(axiBeatBytes).U,
        "NoLLCCHI2AXI ReadNoSnp must fit in one AXI beat")
    }
    when (isNoSnpWriteFull) {
      assert(upstreamReq.bits.size === log2Ceil(lineBytes).U,
        "NoLLCCHI2AXI WriteNoSnpFull must be 64 bytes")
      assert(upstreamReq.bits.addr(5, 0) === 0.U,
        "NoLLCCHI2AXI WriteNoSnpFull must be cache-line aligned")
    }
  }

  when (allocate) {
    val slot = slots(allocSlot)
    slot.valid := true.B
    slot.kind := MuxCase(kindLocal, Seq(
      isCohRead -> kindCohRead,
      isCohWrite -> kindCohWrite,
      isNoSnpRead -> kindNoSnpRead,
      isNoSnpWrite -> kindNoSnpWrite
    ))
    slot.addr := upstreamReq.bits.addr
    slot.size := upstreamReq.bits.size
    slot.reqTxnID := upstreamReq.bits.txnID
    slot.reqSrcID := upstreamReq.bits.srcID
    slot.qos := upstreamReq.bits.qos
    slot.traceTag := upstreamReq.bits.traceTag
    slot.responseState := Mux(isCohRead || isMakeUnique, UC, I)
    slot.expCompAck := upstreamReq.bits.expCompAck
    slot.ackSeen := false.B
    slot.ownsReqTxnID := true.B
    slot.orderedNoSnp := incomingOrderedNoSnp
    slot.readReceiptNeeded := isNoSnpRead && upstreamReq.bits.order =/= OrderEncodings.None
    slot.arIssued := false.B
    slot.readBeatsAccepted := 0.U
    slot.readFirstDelivered := false.B
    slot.readLastDelivered := false.B
    slot.rspSent := false.B
    slot.rspDelivered := false.B
    slot.earlyWriteComp := isCohWrite || isNoSnpWrite && upstreamReq.bits.memAttr.ewa
    slot.awIssued := false.B
    slot.writeDataSent := false.B
    slot.bDone := false.B
    slot.writeCompSent := false.B
    slot.writeCompDelivered := false.B
    accepted := accepted + 1.U
  }

  // Read address scheduling is explicitly held while AXI applies backpressure.
  val arSelectValid = RegInit(false.B)
  val arSelect = RegInit(0.U(slotBits.W))
  val arArb = Module(new RRArbiter(UInt(slotBits.W), entries))
  arArb.io.in.zipWithIndex.foreach { case (in, i) =>
    in.valid := slots(i).valid &&
      (slots(i).kind === kindCohRead || slots(i).kind === kindNoSnpRead) && !slots(i).arIssued
    in.bits := i.U
  }
  arArb.io.out.ready := !arSelectValid
  when (arArb.io.out.fire) {
    arSelectValid := true.B
    arSelect := arArb.io.out.bits
  }

  val arIsCoh = slots(arSelect).kind === kindCohRead
  axi.ar.valid := arSelectValid
  axi.ar.bits := 0.U.asTypeOf(axi.ar.bits)
  axi.ar.bits.id := paddedSlotID(arSelect)
  axi.ar.bits.addr := slots(arSelect).addr
  axi.ar.bits.len := Mux(arIsCoh, (beatsPerLine - 1).U, 0.U)
  axi.ar.bits.size := Mux(arIsCoh, log2Ceil(axiBeatBytes).U, slots(arSelect).size)
  axi.ar.bits.burst := BURST_INCR
  axi.ar.bits.cache := Mux(
    arIsCoh,
    CACHE_RALLOCATE | CACHE_WALLOCATE | CACHE_MODIFIABLE | CACHE_BUFFERABLE,
    CACHE_MODIFIABLE | CACHE_BUFFERABLE
  )
  axi.ar.bits.prot := "b010".U
  axi.ar.bits.qos := slots(arSelect).qos
  when (axi.ar.fire) {
    assert(slots(arSelect).valid &&
      (slots(arSelect).kind === kindCohRead || slots(arSelect).kind === kindNoSnpRead) &&
      !slots(arSelect).arIssued)
    slots(arSelect).arIssued := true.B
    arSelectValid := false.B
  }

  // AXI read data is buffered before entering the CHI L-credit link.
  val readDataQueue = Module(new Queue(new ReadDataEntry, entries = 4, pipe = true, flow = false))
  val rIDInRange = axi.r.bits.id < entries.U
  val rSlot = slotID(axi.r.bits.id)
  val rIsCoh = slots(rSlot).kind === kindCohRead
  val rExpectedBeats = Mux(rIsCoh, beatsPerLine.U, 1.U)
  val rSlotValid = rIDInRange && slots(rSlot).valid &&
    (rIsCoh || slots(rSlot).kind === kindNoSnpRead) && slots(rSlot).arIssued &&
    slots(rSlot).readBeatsAccepted < rExpectedBeats
  val rLast = slots(rSlot).readBeatsAccepted === rExpectedBeats - 1.U
  axi.r.ready := rSlotValid && readDataQueue.io.enq.ready
  readDataQueue.io.enq.valid := axi.r.valid && rSlotValid
  readDataQueue.io.enq.bits := 0.U.asTypeOf(new ReadDataEntry)
  readDataQueue.io.enq.bits.slot := rSlot
  readDataQueue.io.enq.bits.last := rLast
  val readDat = readDataQueue.io.enq.bits.dat
  readDat.qos := slots(rSlot).qos
  readDat.tgtID := slots(rSlot).reqSrcID
  readDat.srcID := io.nodeID
  readDat.txnID := slots(rSlot).reqTxnID
  readDat.homeNID := io.nodeID
  readDat.opcode := CompData
  readDat.respErr := RespErrEncodings.OK
  readDat.resp := slots(rSlot).responseState
  readDat.dbID := rSlot
  readDat.dataID := Mux(rIsCoh, slots(rSlot).readBeatsAccepted << 1, slots(rSlot).addr(5) << 1)
  readDat.be := Fill(BE_WIDTH, true.B)
  readDat.data := axi.r.bits.data
  readDat.traceTag := slots(rSlot).traceTag
  readDat.dataCheck.foreach(_ := oddParity(axi.r.bits.data))
  readDat.poison.foreach(_ := 0.U)
  when (axi.r.valid) {
    assert(rSlotValid, "NoLLCCHI2AXI received AXI R for an inactive read slot")
  }
  when (axi.r.fire) {
    assert(axi.r.bits.resp === RESP_OKAY, "NoLLCCHI2AXI received an AXI read error")
    assert(axi.r.bits.last === rLast, "NoLLCCHI2AXI received an invalid AXI RLAST")
    slots(rSlot).readBeatsAccepted := slots(rSlot).readBeatsAccepted + 1.U
  }
  rn.rx.dat.valid := readDataQueue.io.deq.valid
  rn.rx.dat.bits := readDataQueue.io.deq.bits.dat
  readDataQueue.io.deq.ready := rn.rx.dat.ready

  // CHI completion responses are queued so they remain stable across link backpressure.
  val rspQueue = Module(new Queue(new RspEntry, entries = 4, pipe = true, flow = false))
  val writeOwnerValid = RegInit(false.B)
  val writeOwner = RegInit(0.U(slotBits.W))
  val writeData = Reg(Vec(beatsPerLine, UInt(DATA_WIDTH.W)))
  val writeBE = Reg(Vec(beatsPerLine, UInt(BE_WIDTH.W)))
  val writeBeatValid = RegInit(VecInit(Seq.fill(beatsPerLine)(false.B)))
  val writeSendBeat = RegInit(0.U(1.W))

  val rspSelectValid = RegInit(false.B)
  val rspSelect = RegInit(0.U(slotBits.W))
  val rspArb = Module(new RRArbiter(UInt(slotBits.W), entries))
  rspArb.io.in.zipWithIndex.foreach { case (in, i) =>
    val slot = slots(i)
    val initialWriteRsp = (slot.kind === kindCohWrite || slot.kind === kindNoSnpWrite) &&
      !slot.rspSent && !writeOwnerValid
    val readReceipt = slot.kind === kindNoSnpRead && slot.readReceiptNeeded && slot.arIssued && !slot.rspSent
    val finalWriteComp = slot.kind === kindNoSnpWrite && !slot.earlyWriteComp && slot.bDone &&
      !slot.writeCompSent
    in.valid := slot.valid && (slot.kind === kindLocal && !slot.rspSent || initialWriteRsp ||
      readReceipt || finalWriteComp)
    in.bits := i.U
  }
  rspArb.io.out.ready := !rspSelectValid
  when (rspArb.io.out.fire) {
    rspSelectValid := true.B
    rspSelect := rspArb.io.out.bits
  }

  val rspSlot = slots(rspSelect)
  val rspIsInitialWrite = (rspSlot.kind === kindCohWrite || rspSlot.kind === kindNoSnpWrite) &&
    !rspSlot.rspSent
  val rspIsReadReceipt = rspSlot.kind === kindNoSnpRead
  val rspIsFinalWriteComp = rspSlot.kind === kindNoSnpWrite && rspSlot.rspSent
  rspQueue.io.enq.valid := rspSelectValid
  rspQueue.io.enq.bits := 0.U.asTypeOf(new RspEntry)
  rspQueue.io.enq.bits.slot := rspSelect
  val response = rspQueue.io.enq.bits.rsp
  response.qos := rspSlot.qos
  response.tgtID := rspSlot.reqSrcID
  response.srcID := io.nodeID
  response.txnID := rspSlot.reqTxnID
  response.opcode := MuxCase(Comp, Seq(
    rspIsReadReceipt -> ReadReceipt,
    (rspIsInitialWrite && rspSlot.earlyWriteComp) -> CompDBIDResp,
    rspIsInitialWrite -> DBIDResp
  ))
  response.respErr := RespErrEncodings.OK
  response.resp := Mux(
    response.opcode === ReadReceipt || response.opcode === DBIDResp || response.opcode === CompDBIDResp,
    0.U,
    rspSlot.responseState
  )
  response.dbID := rspSelect
  response.traceTag := rspSlot.traceTag
  when (rspQueue.io.enq.fire) {
    rspSelectValid := false.B
    when (rspIsInitialWrite) {
      rspSlot.rspSent := true.B
      assert(!writeOwnerValid)
      writeOwnerValid := true.B
      writeOwner := rspSelect
      writeBeatValid.foreach(_ := false.B)
      writeSendBeat := 0.U
    }.elsewhen (rspIsFinalWriteComp) {
      rspSlot.writeCompSent := true.B
    }.otherwise {
      rspSlot.rspSent := true.B
    }
  }
  rn.rx.rsp.valid := rspQueue.io.deq.valid
  rn.rx.rsp.bits := rspQueue.io.deq.bits.rsp
  rspQueue.io.deq.ready := rn.rx.rsp.ready

  // Only one write owns the CHI data channel and AXI W channel at a time.
  val upstreamData = rn.tx.dat
  val ownerSlot = slots(writeOwner)
  val ownerIsCoh = ownerSlot.kind === kindCohWrite
  val ownerIsNoSnp = ownerSlot.kind === kindNoSnpWrite
  val ownerIsNoSnpFull = ownerIsNoSnp && ownerSlot.size === log2Ceil(lineBytes).U
  val expectedDataOpcode = Mux(ownerIsCoh, CopyBackWrData, NonCopyBackWrData)
  val dataIDSupported = upstreamData.bits.dataID === 0.U || upstreamData.bits.dataID === 2.U
  val noSnpPtlDataID = ownerSlot.addr(5) << 1
  val dataIDMatches = dataIDSupported && Mux(
    ownerIsCoh || ownerIsNoSnpFull,
    true.B,
    upstreamData.bits.dataID === noSnpPtlDataID
  )
  val dataBeat = Mux(ownerIsCoh || ownerIsNoSnpFull, upstreamData.bits.dataID(1), 0.U)
  val canAcceptWriteData = writeOwnerValid && (ownerIsCoh || ownerIsNoSnp) &&
    upstreamData.bits.txnID === writeOwner && upstreamData.bits.opcode === expectedDataOpcode &&
    dataIDMatches && !writeBeatValid(dataBeat)
  upstreamData.ready := canAcceptWriteData
  when (upstreamData.valid) {
    assert(writeOwnerValid, "NoLLCCHI2AXI received write data without a write owner")
    assert(upstreamData.bits.opcode === expectedDataOpcode,
      "NoLLCCHI2AXI received the wrong CHI write-data opcode")
    assert(canAcceptWriteData, "NoLLCCHI2AXI received write data for an invalid DBID or DataID")
  }
  when (upstreamData.fire) {
    assert(ownerSlot.valid && (ownerIsCoh || ownerIsNoSnp))
    when (ownerIsCoh || ownerIsNoSnpFull) {
      assert(upstreamData.bits.be.andR, "NoLLCCHI2AXI full-line writes require full byte enables")
    }.otherwise {
      assert(upstreamData.bits.be.orR, "NoLLCCHI2AXI partial writes require a nonzero byte enable")
    }
    if (enableDataCheck) {
      assert(upstreamData.bits.dataCheck.get === oddParity(upstreamData.bits.data),
        "NoLLCCHI2AXI received write data with invalid DataCheck")
    }
    if (enablePoison) {
      assert(upstreamData.bits.poison.get === 0.U, "NoLLCCHI2AXI does not support poisoned write data")
    }
    writeData(dataBeat) := upstreamData.bits.data
    writeBE(dataBeat) := upstreamData.bits.be
    writeBeatValid(dataBeat) := true.B
  }

  val ownerNeedsTwoBeats = ownerIsCoh || ownerIsNoSnpFull
  val haveAllWriteData = Mux(ownerNeedsTwoBeats, writeBeatValid.asUInt.andR, writeBeatValid(0))
  axi.aw.valid := writeOwnerValid && (haveAllWriteData || ownerSlot.writeDataSent) && !ownerSlot.awIssued
  axi.aw.bits := 0.U.asTypeOf(axi.aw.bits)
  axi.aw.bits.id := paddedSlotID(writeOwner)
  axi.aw.bits.addr := ownerSlot.addr
  axi.aw.bits.len := Mux(ownerNeedsTwoBeats, (beatsPerLine - 1).U, 0.U)
  axi.aw.bits.size := Mux(ownerNeedsTwoBeats, log2Ceil(axiBeatBytes).U, ownerSlot.size)
  axi.aw.bits.burst := BURST_INCR
  axi.aw.bits.cache := Mux(
    ownerIsCoh,
    CACHE_RALLOCATE | CACHE_WALLOCATE | CACHE_MODIFIABLE | CACHE_BUFFERABLE,
    CACHE_MODIFIABLE | CACHE_BUFFERABLE
  )
  axi.aw.bits.prot := "b010".U
  axi.aw.bits.qos := ownerSlot.qos
  when (axi.aw.fire) {
    ownerSlot.awIssued := true.B
  }

  axi.w.valid := writeOwnerValid && haveAllWriteData && !ownerSlot.writeDataSent
  axi.w.bits := 0.U.asTypeOf(axi.w.bits)
  axi.w.bits.data := writeData(writeSendBeat)
  axi.w.bits.strb := writeBE(writeSendBeat)
  axi.w.bits.last := !ownerNeedsTwoBeats || writeSendBeat === (beatsPerLine - 1).U
  val writeLastFire = axi.w.fire && axi.w.bits.last
  val writeAddressDone = ownerSlot.awIssued || axi.aw.fire
  when (axi.w.fire) {
    when (axi.w.bits.last) {
      ownerSlot.writeDataSent := true.B
      writeBeatValid.foreach(_ := false.B)
      writeSendBeat := 0.U
    }.otherwise {
      writeSendBeat := writeSendBeat + 1.U
    }
  }
  when (writeOwnerValid && ((axi.aw.fire && ownerSlot.writeDataSent) ||
    (writeLastFire && writeAddressDone))) {
    writeOwnerValid := false.B
  }

  val bIDInRange = axi.b.bits.id < entries.U
  val bSlot = slotID(axi.b.bits.id)
  val bCompletesCurrentWrite = writeOwnerValid && writeLastFire && writeOwner === bSlot
  val bSlotValid = bIDInRange && slots(bSlot).valid &&
    (slots(bSlot).kind === kindCohWrite || slots(bSlot).kind === kindNoSnpWrite) &&
    (slots(bSlot).writeDataSent || bCompletesCurrentWrite)
  axi.b.ready := bSlotValid
  when (axi.b.valid) {
    assert(bSlotValid, "NoLLCCHI2AXI received AXI B for an inactive write slot")
  }
  when (axi.b.fire) {
    assert(axi.b.bits.resp === RESP_OKAY, "NoLLCCHI2AXI received an AXI write error")
    slots(bSlot).bDone := true.B
  }

  // Release requester TxnID ownership only after the last CHI message carrying that ID.
  val rspOutFire = rspQueue.io.deq.fire
  val rspOutSlot = rspQueue.io.deq.bits.slot
  val rspOutOpcode = rspQueue.io.deq.bits.rsp.opcode
  val dataOutFire = readDataQueue.io.deq.fire
  val dataOutSlot = readDataQueue.io.deq.bits.slot
  val dataOutLast = readDataQueue.io.deq.bits.last
  when (rspOutFire) {
    val slot = slots(rspOutSlot)
    assert(slot.valid, "NoLLCCHI2AXI returned a response for an inactive slot")
    when (rspOutOpcode === ReadReceipt) {
      slot.rspDelivered := true.B
      when (slot.readLastDelivered || dataOutFire && dataOutLast && dataOutSlot === rspOutSlot) {
        slot.ownsReqTxnID := false.B
        slot.valid := false.B
      }
    }.elsewhen (slot.kind === kindLocal) {
      slot.ownsReqTxnID := false.B
      slot.rspDelivered := true.B
      when (!slot.expCompAck) {
        slot.valid := false.B
      }
    }.elsewhen (rspOutOpcode === Comp && slot.kind === kindNoSnpWrite) {
      assert(slot.bDone && !slot.earlyWriteComp)
      slot.writeCompDelivered := true.B
      slot.rspDelivered := true.B
    }.otherwise {
      slot.rspDelivered := true.B
      when (slot.kind === kindCohWrite || slot.earlyWriteComp) {
        slot.ownsReqTxnID := false.B
      }
    }
  }

  when (dataOutFire) {
    val slot = slots(dataOutSlot)
    assert(slot.valid && (slot.kind === kindCohRead || slot.kind === kindNoSnpRead))
    when (dataOutLast) {
      slot.readLastDelivered := true.B
      when (slot.kind === kindCohRead) {
        slot.ownsReqTxnID := false.B
        when (!slot.expCompAck || slot.ackSeen) {
          slot.valid := false.B
        }
      }.otherwise {
        when (!slot.readReceiptNeeded || slot.rspDelivered ||
          rspOutFire && rspOutOpcode === ReadReceipt && rspOutSlot === dataOutSlot) {
          slot.ownsReqTxnID := false.B
          slot.valid := false.B
        }
      }
    }.otherwise {
      slot.readFirstDelivered := true.B
    }
  }

  val upstreamRsp = rn.tx.rsp
  val ackSlotInRange = upstreamRsp.bits.txnID < entries.U
  val ackSlot = slotID(upstreamRsp.bits.txnID)
  val ackSlotValid = ackSlotInRange && slots(ackSlot).valid && slots(ackSlot).expCompAck &&
    (slots(ackSlot).kind === kindCohRead || slots(ackSlot).kind === kindCohWrite ||
      slots(ackSlot).kind === kindNoSnpWrite || slots(ackSlot).kind === kindLocal)
  upstreamRsp.ready := upstreamRsp.bits.opcode === CompAck && ackSlotValid
  when (upstreamRsp.valid) {
    assert(upstreamRsp.bits.opcode === CompAck,
      "NoLLCCHI2AXI only accepts CompAck on CHI TXRSP")
    assert(ackSlotValid, "NoLLCCHI2AXI received CompAck for an inactive DBID")
    when (ackSlotValid && slots(ackSlot).kind === kindCohRead) {
      assert(slots(ackSlot).readFirstDelivered,
        "NoLLCCHI2AXI received read CompAck before the first CompData")
    }
    when (ackSlotValid && slots(ackSlot).kind === kindLocal) {
      assert(slots(ackSlot).rspDelivered,
        "NoLLCCHI2AXI received local CompAck before Comp")
    }
  }
  when (upstreamRsp.fire) {
    assert(!slots(ackSlot).ackSeen, "NoLLCCHI2AXI received a duplicate CompAck")
    slots(ackSlot).ackSeen := true.B
    when (slots(ackSlot).kind === kindLocal || slots(ackSlot).kind === kindCohRead &&
      (slots(ackSlot).readLastDelivered ||
      dataOutFire && dataOutLast && dataOutSlot === ackSlot)) {
      slots(ackSlot).valid := false.B
    }
  }

  // A write slot is released only after its initial CHI response, all write data, AXI B,
  // and any required final CHI response or CompAck have actually completed.
  val writeInitialResponseFire = rspOutFire &&
    (rspOutOpcode === DBIDResp || rspOutOpcode === CompDBIDResp)
  val writeFinalResponseFire = rspOutFire && rspOutOpcode === Comp &&
    rspOutSlot < entries.U && slots(rspOutSlot).kind === kindNoSnpWrite
  for (i <- 0 until entries) {
    val slot = slots(i)
    val initialResponseDone = slot.rspDelivered || writeInitialResponseFire && rspOutSlot === i.U
    val writeDataDone = slot.writeDataSent || writeLastFire && writeOwner === i.U
    val writeBDone = slot.bDone || axi.b.fire && bSlot === i.U
    val finalResponseDone = slot.earlyWriteComp || slot.writeCompDelivered ||
      writeFinalResponseFire && rspOutSlot === i.U
    val compAckDone = !slot.expCompAck || slot.ackSeen || upstreamRsp.fire && ackSlot === i.U
    when (slot.valid && (slot.kind === kindCohWrite || slot.kind === kindNoSnpWrite) &&
      initialResponseDone && writeDataDone && writeBDone && finalResponseDone && compAckDone) {
      slot.ownsReqTxnID := false.B
      slot.valid := false.B
    }
  }
}
