# This file describes the GitHub Actions workflow for continuous integration of XS Core.
name: EMU Test

on:
  push:
    branches: [ master, dev-v0.6 ]
  pull_request:
    branches: [ master, dev-v0.6 ]

env:
  CI_HOME: /nfs/home/ci-runner/xsai-emu/${{ github.run_number }}

jobs:
  changes: # Changes Detection
    name: Changes Detection
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      core: ${{ steps.filter.outputs.core }}
    steps:
    - uses: actions/checkout@v7
    - uses: dorny/paths-filter@v4
      id: filter
      with:
        predicate-quantifier: 'every'
        filters: .github/filters.yaml

  generate-verilog:
    runs-on: bosc
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    continue-on-error: false
    timeout-minutes: 900
    name: Generate XSAI Verilog
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: set env
        run: |
          JOB_HOME="${CI_HOME}/generate-verilog"
          echo "NOOP_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "NEMU_HOME=/nfs/home/share/ci-workloads/NEMU" >> $GITHUB_ENV
          echo "WAVE_HOME=${JOB_HOME}" >> $GITHUB_ENV
          mkdir -p "${JOB_HOME}"
      - name: Initialize submodules
        run: make init-force
      - name: clean up
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: check top wiring
        run:
          bash .github/workflows/check-usage.sh "BoringUtils" $GITHUB_WORKSPACE
      - name: generate standalone devices for TL
        run: |
          make StandAloneCLINT DEVICE_BASE_ADDR=0x38000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=CLINT_
          make StandAloneSYSCNT DEVICE_BASE_ADDR=0x38040000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=CLINT_
          make StandAloneDebugModule DEVICE_BASE_ADDR=0x38020000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=DM_
          make StandAlonePLIC DEVICE_BASE_ADDR=0x3C000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=PLIC_
          make clean
      - name: generate standalone devices for AXI4
        run: |
          make StandAloneCLINT DEVICE_BASE_ADDR=0x38000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=CLINT_
          make StandAloneSYSCNT DEVICE_BASE_ADDR=0x38040000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=CLINT_
          make StandAloneDebugModule DEVICE_BASE_ADDR=0x38020000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=DM_
          make StandAlonePLIC DEVICE_BASE_ADDR=0x3C000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=PLIC_
          make clean
      - name: generate verilog file
        run:
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --generate --num-cores 2 --config DefaultMatrixConfig
      - name: check verilog
        run: |
          python3 $GITHUB_WORKSPACE/.github/workflows/check_verilog.py build/rtl
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: generate chirrtl only
        run: |
          make sim-verilog CHISEL_TARGET=chirrtl CONFIG=DefaultMatrixConfig
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: build MinimalMatrixConfig Release emu
        run: |
          sed -i \
            -e 's/--output-split 30000/--output-split 5000/' \
            -e 's/--output-split-cfuncs 30000/--output-split-cfuncs 5000/' \
            -e 's/OPT_FAST ?= -O3/OPT_FAST ?= -O3\\ -fno-vectorize\\ -fno-slp-vectorize/' \
            $GITHUB_WORKSPACE/difftest/verilator.mk
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build \
            --threads 8 --config MinimalMatrixConfig --release --trace-fst
      - name: run MinimalMatrixConfig - Linux
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 8 --numa --ci linux-hello-opensbi 2> perf.log
          cat perf.log | sort

  emu-xsai-basics:
    runs-on: bosc
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    continue-on-error: false
    timeout-minutes: 900
    name: EMU - XSAI Basics
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: set env
        run: |
          JOB_HOME="${CI_HOME}/basics"
          echo "NOOP_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "NEMU_HOME=/nfs/home/share/ci-workloads/NEMU" >> $GITHUB_ENV
          echo "AM_HOME=/nfs/home/share/ci-workloads/nexus-am" >> $GITHUB_ENV
          echo "PERF_HOME=${JOB_HOME}" >> $GITHUB_ENV
          echo "WAVE_HOME=${JOB_HOME}" >> $GITHUB_ENV
          echo "GCPT_RESTORE_BIN=/nfs/home/share/ci-workloads/fix-gcpt/gcpt.bin" >> $GITHUB_ENV
          mkdir -p "${JOB_HOME}"
      - name: Initialize submodules
        run: make init-force
      - name: clean up
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: Build EMU
        run: |
          sed -i \
            -e 's/--output-split 30000/--output-split 5000/' \
            -e 's/--output-split-cfuncs 30000/--output-split-cfuncs 5000/' \
            -e 's/OPT_FAST ?= -O3/OPT_FAST ?= -O3\\ -fno-vectorize\\ -fno-slp-vectorize/' \
            $GITHUB_WORKSPACE/difftest/verilator.mk
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build --threads 8 \
            --config DefaultMatrixConfig --pgo $GITHUB_WORKSPACE/ready-to-run/coremark-2-iteration.bin --llvm-profdata llvm-profdata --trace-fst
      - name: Basic Test - cputest
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --ci cputest 2> /dev/zero
      - name: Basic Test - riscv-tests
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --rvtest /nfs/home/share/ci-workloads/riscv-tests --ci riscv-tests 2> /dev/zero
      - name: Basic Test - misc-tests
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci misc-tests 2> /dev/zero
      - name: Basic AME Test
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci ame-tests 2> /dev/zero
      - name: Extension Test - hypervisor
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci rvh-tests 2> /dev/zero
      - name: Simple Test - microbench
        id: microbench
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --ci microbench 2> perf.log | tee stdout.log
          cat perf.log | sort | tee $PERF_HOME/microbench.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: Simple Test - CoreMark
        id: coremark
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci coremark 2> perf.log | tee stdout.log
          cat perf.log | sort | tee $PERF_HOME/coremark.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: System Test - Linux
        id: linux
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci linux-hello-opensbi 2> perf.log | tee stdout.log
          cat perf.log | sort | tee $PERF_HOME/linux.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: Floating-point Test - povray
        id: povray
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --max-instr 5000000 --ci povray --gcpt-restore-bin $GCPT_RESTORE_BIN 2> perf.log | tee stdout.log
          cat perf.log | sort | tee $PERF_HOME/povray.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: Uncache Fetch Test - copy and run
        id: copy_and_run
        run: |
          $GITHUB_WORKSPACE/build/emu  -F $GITHUB_WORKSPACE/ready-to-run/copy_and_run.bin -i $GITHUB_WORKSPACE/ready-to-run/microbench.bin --diff $GITHUB_WORKSPACE/ready-to-run/riscv64-nemu-interpreter-so --enable-fork 2> perf.log | tee stdout.log
          cat perf.log | sort | tee $PERF_HOME/copy_and_run.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: VFEXP2 Extension Test - vfexp2test
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci vfexp2test 2> /dev/zero
      - name: V Extension Test - rvv-bench
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci rvv-bench 2> /dev/zero
      - name: F16 Test - f16_test
        run: |
          python3 ./scripts/xiangshan.py --wave-dump ./build --thread 16 --numa --ci f16_test 2> /dev/zero
      - name: Zcb Extension Test - zcb-test
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --ci zcb-test 2> /dev/zero
      - name: Generate summary
        if: always()
        run: |
          echo "## Emu - Basics summary" >> $GITHUB_STEP_SUMMARY
          echo "| Testcase | IPC |" >> $GITHUB_STEP_SUMMARY
          echo "| -------- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| microbench | ${{ steps.microbench.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY
          echo "| coremark | ${{ steps.coremark.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY
          echo "| linux | ${{ steps.linux.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY
          echo "| povray | ${{ steps.povray.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY
          echo "| copy_and_run | ${{ steps.copy_and_run.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: changes
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build docker image
        run: make image

      - name: Compile generator JAR
        run: make test-jar

  emu-xsai-mc:
    runs-on: bosc
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    continue-on-error: false
    timeout-minutes: 900
    name: EMU - XSAI MC
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: true
      - name: set env
        run: |
          JOB_HOME="${CI_HOME}/mc"
          echo "NOOP_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "NEMU_HOME=/nfs/home/share/ci-workloads/NEMU" >> $GITHUB_ENV
          echo "AM_HOME=/nfs/home/share/ci-workloads/nexus-am" >> $GITHUB_ENV
          echo "PERF_HOME=${JOB_HOME}" >> $GITHUB_ENV
          echo "WAVE_HOME=${JOB_HOME}" >> $GITHUB_ENV
          mkdir -p "${JOB_HOME}"
      - name: Initialize submodules
        run: make init-force
      - name: clean up
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: Build MC EMU
        run: |
          sed -i \
            -e 's/--output-split 30000/--output-split 5000/' \
            -e 's/--output-split-cfuncs 30000/--output-split-cfuncs 5000/' \
            -e 's/OPT_FAST ?= -O3/OPT_FAST ?= -O3\\ -fno-vectorize\\ -fno-slp-vectorize/' \
            $GITHUB_WORKSPACE/difftest/verilator.mk
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build \
            --num-cores 2 --emu-optimize "" --config DefaultMatrixConfig \
            --dramsim3 /nfs/home/share/ci-workloads/DRAMsim3 --with-dramsim3 --threads 8 \
            --pgo /nfs/home/share/ci-workloads/linux-hello-smp-new/bbl.bin --llvm-profdata llvm-profdata --trace-fst
      - name: MC Test
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --diff ./ready-to-run/riscv64-nemu-interpreter-dual-so --ci mc-tests 2> /dev/zero
      - name: SMP Linux
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 16 --numa --diff ./ready-to-run/riscv64-nemu-interpreter-dual-so --ci linux-hello-smp-new 2> /dev/null

  scalafmt:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    continue-on-error: true
    timeout-minutes: 900
    name: Check Format
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: 'recursive'
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'
      - run: |
          mkdir -p ~/.local/bin
          sh -c "curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.7/0.11.7 > ~/.local/bin/mill && chmod +x ~/.local/bin/mill"
          export PATH=~/.local/bin:$PATH
      - run: make check-format
